# Generated by Django 4.2.7 on 2023-11-10 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payrollapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step1Sub2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(max_length=255)),
                ('company_pan', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step1Sub4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('organization_type', models.CharField(choices=[('private', 'Private'), ('govt', 'Government')], max_length=10, verbose_name='Organization Type*')),
                ('company_gstin', models.CharField(blank=True, help_text='If you want to change, go back and change GST Number.', max_length=15, null=True, verbose_name='Company GSTIN')),
                ('company_pan', models.CharField(help_text='It should be ten characters long. The first five characters should be any upper case alphabets. The next four characters should be any number from 0 to 9. The last (tenth) character should be any upper case alphabet. It should not contain any white spaces.', max_length=10, verbose_name='Company PAN')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('registered_address', models.TextField(verbose_name='Registered Address')),
                ('pincode', models.CharField(help_text='It can be only six digits. It should not start with zero. First digit of the pin code must be from 1 to 9. Next five digits of the pin code may range from 0 to 9. It should allow only one white space, but after three digits, although this is optional.', max_length=10, verbose_name='Pincode')),
                ('state', models.CharField(choices=[('state-a', 'State A'), ('state-b', 'State B'), ('state-c', 'State C')], max_length=20, verbose_name='State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step1Sub3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('work_address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(default='', max_length=10, validators=[payrollapp.models.validate_pincode])),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh')], default='Andhra Pradesh', max_length=255)),
                ('step1_sub2_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step1_sub3_data', to='payrollapp.step1sub2')),
            ],
        ),
        migrations.CreateModel(
            name='Step1Sub1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_gstin', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_login', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
