# Generated by Django 4.2.7 on 2023-11-18 17:23

from django.db import migrations, models
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0008_userprofile_first_name_alter_step1sub3_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='addone_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hiring_date', models.DateField()),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('manager', models.CharField(blank=True, choices=[('emp01', 'Employee 01'), ('emp02', 'Employee 02')], max_length=20)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, choices=[('state01', 'State 01'), ('state02', 'State 02')], max_length=20)),
                ('resident_of_india', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='step1sub3',
            name='pincode',
            field=models.CharField(default='', max_length=10, validators=[payrollapp.models.validate_pincode]),
        ),
    ]
