# Generated by Django 4.2.7 on 2023-11-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0011_employee_delete_addoneemployee_and_more'),
    ]

    operations = [
    ]
