# Generated by Django 4.2.7 on 2023-11-20 12:17

from django.db import migrations, models
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0014_employee_account_number_employee_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='step1sub3',
            name='pincode',
            field=models.CharField(default='', max_length=10, validators=[payrollapp.models.validate_pincode]),
        ),
    ]
